services:
  - type: web
    name: finsense-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: PORT
        value: 10000
